#+Title: Data-Driven Model Structure Notes
#+Author: Ben Heinze

# Removes the Table of Contents
#+OPTIONS: toc:nil

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}


* Intro 

How do we visualize multivariate data?

Random effects (top level; subject level; i): grouping structure var to account for random selection of groups. Usually drives the structure of model.
Fixed effects (bottom level; observation level; ij ): exerpiment or the subjects being tested. Usually the reason for fitting the model

Hierarchy consists of the levels of random effect at the top, and the observations (fixed effects) within each group at the bottom. Adding more random effects makes it more complex, like a tree-like structure. New perspective on model calling randome effects "varying coefficients in a multilevel model".

Visualizing multivariate data: bivariate graph that points reponse againse 1 or more fixed efects at a time.

2simultaneous multivariate data vis techniques use table plots and alluvial plots, but these are hard to visualize the different roles and contributioons the REs and the hierarchy have with both fixed effect and response variable. Complexity makes this issue worse.

You can make model visualizations of the data itself by hand, or iuse DiagrammeR, but this is tedious. LLMs could be used but they still need verification. modeldiagramR solves this issue (nice plug).

** Linear Mixed Effects Models

matched pair design: treatment is applied at the observation level.



* Question 1.

Weight only needs the single subscript $i$ because that is going to remain constant through each sweat measurement, so they only need to account for it on the subject level. The no-tattoo indicator, on the other hand, will change despite the subject being the same, so this is on the observation level.

* Question 2.

If the classmate used $age_{ij}$ despite it being measured one per subject, at the observation level, /modeldiagramR/ uses data to generate a corrected model diagram by checking if the value is constant across the random effects level for a node. 
  
The software can determine if the predictor values are repeated for a fixed effect by checking if the value is constant across the random effects level for a node.


* Question 3.

I'd use the LearnVizLMM package to check the model diagram fro lab 7 before cleaning and wrangling the data because it doesn't require the data or a model object to draw the diagram.


* Question 4

1. measurement structure diagram
   - top level and bottom level to describe observations in data set
   - Column for fixed effects and random effects
   - Define i and j.
2. Write theoretical model to address RQ
   - define all variables and indices
3. Identify and interpret model parameters to address RQ.

** Subquestion 1

Measurement structure:
- top level i: person1, ..., person 25
- bottom level ij: 5 repeated measurements
- fixed effects column:
  - people @SU level (x_i)  (since RQ cares about relationship between IQ and beer consumption, not variability in people)
  - Time they took quiz, liters of beer consumed @obs level (x_ij)
- random effects column: SU_i, \epsilon_{ij}
- i = 1-25 (index people)
- j = 1-12, (index observation within people (liters of beer for number of tests took))


Theoretical model:
$\text{IQScore_{ij}} = \mu_{ij} + SU_{i} + \epsilon_{ij}$
$\mu_{ij} = \beta_0 + \beta_1 I_{test 2} + \ldots + \beta_11 I_{test 12} + \beta_13 \text{beer_liters}}$
$SU_{i} \sim \mathcal{N} (0, \sigma^2_{person})$
$\epsilon_{ij} \sim \mathcal{N} (0, \sigma^2)$

Model params: 
\beta_0: expected IQ for someone who doesn't drink



   
** Subproblem 2.

Measurement structure:
- top level i: 15 states
- middle level j: 20 counties within state
- bottom level ijk: 50 households within county within state

Fixed effects: youngest household age(?), political-leaning (county),  
Random effects: State, county, households, per-person-adjusted household income




- SU level (x_ij): state, county, political-leaning
- Observation level (x_ijk): youngest household age, per-person adjusted household income, household
- random effects column: SU_i, \epsilon_{ijk}
- i = 1-15 (index state)
- j = 1-20 (index county)
- k = 1-50 (index households)


Theoretical model:
$\text{Diff_{ij}} = \mu_{ijk} + SU_{ij} + \epsilon_{ijk}$
$\mu_{ijk} = \beta_0 + \beta_1 I_{test 2}  $

$SU_{i} \sim \mathcal{N} (0, \sigma^2_{person})$
$\epsilon_{ij} \sim \mathcal{N} (0, \sigma^2)$

Model params:
\beta_0: 
