#+title: Data-Driven Model Structure Notes
#+Author: Ben Heinze

# Removes the Table of Contents
#+OPTIONS: toc:nil

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}

* Question 1.

Weight only needs the single subscript $i$ because that is going to remain constant through each sweat measurement, so they only need to account for it on the subject level. The no-tattoo indicator, on the other hand, will change despite the subject being the same, so this is on the observation level.

* Question 2.

If the classmate used $age_{ij}$ despite it being measured one per subject, at the observation level, /modeldiagramR/ uses data to generate a corrected model by creating a model diagram based on the data, which would make this student's mistake clearly visible. 


* Question 3.

I'd use the LearnVizLMM package to check the model diagram fro lab 7 before cleaning and wrangling the data because it doesn't require the data or a model object to draw the diagram.


* Question 4

1. measurement structure diagram
   - top level and bottom level to describe observations in data set
   - Column for fixed effects and random effects
   - Define i and j.
2. Write theoretical model to address RQ
   - define all variables and indices
3. Identify and interpret model parameters to address RQ.

** Subquestion 1

Measurement structure:

- fixed effects column:
  - people @SU level (x_i)
  - Time they took quiz, liters of beer consumed @obs level (x_ij)
- random effects column: SU_i, \epsilon_{ij}
- i = 1-25 (index people)
- j = 1-12, (index observation within people (number of tests taken))


Theoretical model:
$\text{IQScore}_{ij} = \mu_{ij} + Person_{i} + \epsilon_{ij}$
$\mu_{ij} = \beta_0 + \beta_1 I_{test 2} + \ldots + \beta_11 I_{test 12} + \beta_13 \text{beer_liters}}$
$SU_{i} \sim \mathcal{N} (0, \sigma^2_{person})$
$\epsilon_{ij} \sim \mathcal{N} (0, \sigma^2)$

Model params: 
\beta_0: expected IQ for someone who doesn't drink
\beta_i = the change in intercept for test i compared to baseline
\beta_13 = the change in intercept compared to baseline given the liter of beer they drank in the last two weeks.



   
** Subproblem 2.

Measurement structure:
- top level i: 15 states
- middle level j: 20 counties within state
- bottom level ijk: 50 households within county within state

Fixed effects: youngest household age(?), political-leaning (county),  
Random effects: State, county, households, per-person-adjusted household income



- SU level (x_ij): state, county, political-leaning
- Observation level (x_ijk): youngest household age, per-person adjusted household income, household
- random effects column: SU_i, \epsilon_{ijk}
- i = 1-15 (index state)
- j = 1-20 (index county)
- k = 1-50 (index households)


Theoretical model:
$\text{Diff_{ij}} = \mu_{ijk} + State_{i} + county_{ij} + household_{ijk} + \epsilon_{ijk}$
$\mu_{ijk} = \beta_0 + \beta_1 I_{test 2}  $

$SU_{i} \sim \mathcal{N} (0, \sigma^2_{person})$
$\epsilon_{ij} \sim \mathcal{N} (0, \sigma^2)$

Model params:
\beta_0: 
