---
title: 'STAT X12: Homework 3'
author: "Part I (Individual) due: Friday, 4/10, 5pm, Part II (Group) due: Friday, 4/17" 
output: pdf_document
fontsize: 12 pt
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, message = FALSE)
```


## Part I - Variable Selection (turn in individually to GS, due 4/10)

Read, _Data-Driven Model Structure Diagrams for Hierarchical Linear Mixed Models_ (Linse et. al, 2026). Then answer the following questions. 

1. (4 pts) In the matched pairs design example modeling sweat rate as a function of tattoo (yes/no) and other covariates, why does _weight_ have only an _i_ subscript, while the _indicator for no tattoo_ has an _ij_ subscript? 

2. (4 pts) Suppose one of your classmates shows you a diagram for the matched pairs design example modeling sweat rate as a function of tattoo (yes/no) and other covariates. In their diagram, they have _age_, which is measured just once per subject, at the observation level and they include an _ij_ subscript on _age_ in their theoretical model. Explain how  `modeldiagramR` uses the data to generate a corrected model diagram that would help you remedy your classmate's error.

3. (2 pts) Which package `modeldiagramR` or `LearnVizLMM` would have allowed you to easily check the model diagram you drew for Lab 7 (i.e., before cleaning and wrangling data)? Bonus points if you use it and provide a check on your model diagram here. 

For each of the scenarios below, (a) __5 pts__ create a measurement structure diagram (as we've been doing in class) to describe the observations in the data set. Be sure to include columns for fixed and random effects, and well-defined subscripts; (b) __5 pts__ write a theoretical model using proper notation that allows you to address the research question. Make sure all all variables and indices are well defined; and (c) __5 pts__ identify and interpret model parameters that allow the researchers to address the question(s) of interest. ___You may knit this lab to a word document to turn it in so that you can include photos of your neatly handwritten model structure diagrams and theoretical models if you would like (i.e., you do not need to complete the following problems in the .Rmd file).___ 

1. __(10 pts)__ Consider a study on the impact that alcohol consumption may have on a person's IQ. Twenty-five people were recruited for this study that took place over five years. Over the course of the study, each person took twelve IQ tests at randomly selected times, with IQ scores being recorded from each (with units of "points"). At the time of each test, participants were asked to report the amount of alcohol (specifically beer) they consumed in the previous two weeks, which was then recorded as the amount of beer consumed (liters). Researchers are specifically interested in the relationship between IQ and the amount of beer consumed, after accounting for subject-to-subject variability. 

2. __(10 pts)__ Consider a study in the US where fifteen states were selected at random. Within each state, twenty counties were selected at random for the study. Finally, fifty randomly sampled households within each county were surveyed. The political leaning of each selected county in the last presidential election (left-leaning if majority went for Biden and right-leaning if majority went for trump) was recorded along with the age of the youngest person in the household (years), and the per-person-adjusted household income (units = $1000/person). Interest lies in if there are differences among the mean adjusted incomes for households in the US in left-leaning counties vs. those in the right-leaning counties, after accounting for the age of the youngest person in the household. 


## Part II - Report (turn in with your lab group to Canvas dropbox, due 4/17)

__Instructions:__ This part of the assignment ***must be completed in your group***. Please rotate the roles within your group from those you assumed on in previous Labs and ***include a group-contribution statement as a final section to your report, briefly describing the role and/or contribution of each team member.*** 

_Write a statistical report for the analysis you conducted in Labs 7,8, and 9. Please include all figures and tables __inline__ with your writing._ 

## Report Rubric

\begin{enumerate}
 \item[I.] {\bf Introduction (10 pts)}:
     \begin{itemize}
       \item Give a brief background of the research problem and description of of the study design.
       \item Clearly outline the question(s) of interest you will address with the statistical analysis.  The more specific you define the question of interest here, the easier the rest of the analysis is.
     \end{itemize}
     
   \item[II.] {\bf Statistical Procedures Used (10 pts)}
   \begin{itemize}
        \item This section should lay out the steps, decisions, and logic for making those decisions leading to the final model used to address questions of interest. The following should be included, and should be written up in a coherent report format.
      \item Describe the response variable and explanatory variables, the details of the study design (concept diagrams can be helpful here) identifying any design variables and describing the measurement structure of the data (if applicable). 
      \item Describe the theoretical statistical model you will use to address the each research question, identifying which parameters allow you to address the research question (define parameters of interest in words).  
       \item Conduct EDA (exploratory data analysis) and create appropriate plots of the raw data. Describe what you learn from the plots and include figure captions for your plots. 
      \item Describe any statistical procedures you will use to make inference related to the research question (e.g. two-sample t-test, analysis of variance, extra sum-of-squares F-test, etc). Be specific about which procedures (and parameters in models) are addressing which questions of interest (if there are multiple questions).
       \item Describe how you assessed assumptions, what your conclusions regarding the assumptions are, and justify your conclusions.  Refer to the appropriate plots and include pertinent plots that are in addition to EDA plots (QQ-plots, residual plots, etc.)
     \end{itemize}
     
    \item[III.] {\bf Summary of Statistical Findings (10 pts)}
    \begin{itemize}
       \item Write up your \emph{Summary of Statistical Findings} for each question of interest.  Follow examples in \emph{The Sleuth} and the information in \emph{Writing a Summary of Statistical Findings} handout.
       \item You can usually do this in two sentences: (1) Interpret the $p$-value in an ``evidence'' sentence and (2) provide and interpret point estimates and confidence intervals in the ``it is estimated'' sentence.
       \item Do NOT use the word \emph{significant} (the s-word) in any of its forms.  Replace the s-word with words describing what you actually mean by it.  Also try to avoid using the word \emph{determine} in the contexts of addressing questions of interest because they can never be definitively answered. Only use the word \emph{correlation} if you are actually calculating one!
     \end{itemize}
     
    \item[IV.] {\bf Conclusion in context (i.e., with appropriate Scope of Inference) (10 pts)} 
      \begin{itemize}
       \item Write a brief \emph{Conclusion statement that includes the appropriate Scope of Inference}.  See examples given in \emph{The Sleuth} and in the \emph{Scope of Inference writing examples} handout.  Specifically, answer these two questions and comment on their implications:
         \begin{enumerate}
            \item  Were the units randomly selected from some larger population? (i.e. What, if any, larger population can you infer the results to?)
            \item  Were the units randomly assigned to groups? (i.e. Are cause-and-effect statements justified?)
         \end{enumerate}
         \item Make sure you write the \emph{Scope of Inference} specific to the language of the problem (\emph{not} just generic statements).  For example, DO NOT say ``There was no randomization so cause and effect statements cannot be made.''  Instead, for example, say ``The lizards were not randomly assigned to diets, therefore we can not conclude that the fly diet caused any increase in average weight over the lizards on the tofu diet.''
     \end{itemize}

\end{enumerate}

 \begin{itemize}
   \item {\bf OTHER (10 pts)} :
     \begin{itemize}
       \item {\bf Style}: Report must be written in complete sentences in paragraph format.  Use the above four headings in your report so that it is clearly organized. Part of the grade for reports is based on writing (organization, grammar, appropriate use of statistical terms, etc.)
       \item {\bf Length}:  The body of the report should be \underline{no more than 5 pages double spaced, including selected figures}!
       \item {\bf Appendix}: Please include R-code (as little as is necessary) in your appendix. Use different specifications in the code chunks to hide code in the main text and show code in the appendix. For example, in the exploratory data analysis chunk, you may have the following specifications, \texttt{```\{r eda, echo = FALSE, results = "hide"\}} and the corresponding code chunk in the appendix will be exactly the same, but with a different name and different specifications, \texttt{```\{r eda-appendix, echo = TRUE, results = "asis"\}}. \emph{Note, you'll get an error when you try to compile if two code chunks have the same name, so be sure to adjust the name of the copied code chunk that goes in the appendix!}
       \item Use the comments provided on labs and homework to improve subsequent reports and assignments!
        \item \underline{don't forget your group collaboration/contribution statement!} 
     \end{itemize}
 \end{itemize}